[
  ["mqtt", "o", {title: "MQTT settings"}],
  ["mqtt.enable", "b", false, {title: "Enable MQTT"}],
  ["mqtt.server", "s", "iot.eclipse.org:1883", {title: "MQTT server"}],
  ["mqtt.client_id", "s", "", {title: "ClientID t send to the broker. Defaults to device.id."}],
  ["mqtt.user", "s", "", {title: "User name"}],
  ["mqtt.pass", "s", "", {title: "Password"}],
  ["mqtt.reconnect_timeout_min", "i", 2, {title: "Starting reconnect timeout"}],
  ["mqtt.reconnect_timeout_max", "i", 60, {title: "Maximum reconnect timeout"}],
  ["mqtt.ssl_cert", "s", "", {title: "Client certificate to present to the server"}],
  ["mqtt.ssl_key", "s", "", {title: "Private key corresponding to the certificate"}],
  ["mqtt.ssl_ca_cert", "s", "", {title: "Verify server certificate using this CA bundle"}],
  ["mqtt.ssl_cipher_suites", "s", "", {title: "Cipher suites to offer to the server"}],
  ["mqtt.ssl_psk_identity", "s", "", {title: "PSK identity (must specify PSK cipher suites)"}],
  ["mqtt.ssl_psk_key", "s", "", {title: "PSK key"}],
  ["mqtt.clean_session", "b", true, {title: "Clean Session"}],
  ["mqtt.keep_alive", "i", 60, {title: "Keep alive interval"}],
  ["mqtt.will_topic", "s", "", {title: "Will topic"}],
  ["mqtt.will_message", "s", "", {title: "Will message"}],
  ["debug.stdout_topic", "s", "", {title: "MQTT topic to publish STDOUT to"}],
  ["debug.stderr_topic", "s", "", {title: "MQTT topic to publish STDERR to"}],
]
